---
title: "Syllabus"
---

Syllabus and materials for the UniBas Autumn 2021 semester on programming experiments in **Inquisit**.

- **Course meeting time**: Mondays, 16:15 to 17:45, Missionsstrasse 64a, Computerraum 00.010
- **Instructor**: Dr. Laura Fontanesi, [laura.fontanesi@unibas.ch](mailto:laura.fontanesi@unibas.ch)

### Schedule and assignments
Your homework for each class period is to actively read the material for that week (if listed below). All of the work you turn in will be done **in class** as WPAs (Weekly Programming Assignments). New WPAs and readings will be uploaded weekly, so check back regularly.

| Week | Date | Topic | Readings | Assignment (in class) |
| ------ | ------ | ------------------------ | ----------------- | ---------------------- |
| 1  | 20 September | Introduction to Inquisit | - | [WPA 1](https://laurafontanesi.github.io/programming_experiments_seminar/wpa1.html) |
| 2  | 27 September | Experimental Designs | - | - |
| 3  | 4 October | Inquisit elements | - | - |
| 4  | 11 October | Events in a trial | - | - |
| 5  | 18 October | Within-subjects manipulation | - | - |
| 6  | 25 October | Across-subject manipulation | - | - |
| 7  | 1 November | Advanced Inquisit topic or Psychopy | - | - |
| 8  | 8 November | Advanced Inquisit topic or Psychopy | - | - |
| 9  | 15 November | Advanced Inquisit topic or Psychopy | - | - |
| 10  | 22 November | Work on final project | - | - |
| 11  | 29 November | Work on final project | - | - |
| 12  | 6 December | Work on final project | - | - |
| 13  | 13 December | Final project presentations | - | - |
| 14  | 20 December | Final project presentations | - | - |

Find the solutions of the weekly assignments [HERE](https://github.com/laurafontanesi/programming_experiments_seminar/tree/main/answers).

### Important Links
Link | Description 
------------- | -------------------- | ----------------------------------- 
[Inquisit 5 documentation](https://www.millisecond.com/support/docs/v5/html/viewer.htm#main.htm) | Documentation of Inquisit 5.
[Millisecond test Library](https://www.millisecond.com/download/library/) | Library of common Experiments programmed in Inquisit.
[Inquisit Forums](https://www.millisecond.com/forums/Forum101.aspx) | Forums where people ask questions about programming in Inquisit.
[Ron Dotsch Tutorial](http://www.rondotsch.nl/inquisit-tutorial/) | A good tutorial on programming a simple experiment.


### Course Description
[Inquisit](https://www.millisecond.com/) is a [proprietary software](https://en.wikipedia.org/wiki/Proprietary_software) for the presentation of psychological experiments, both online (on platforms such as Amazon Turk or Prolific) as well as in the lab. It is designed to be relatively easy to learn (meaning that no specific prior programming knowledge is required) and it delivers precise response or reaction times measurements.

The goal of this course is to introduce you to Inquisit so that you can apply it to your current and future research. Because Inquisit is a proprietary software, you will not be able to use it on your laptop. You will however be able to use it on the computers in the computer room, so all the practical work is done in class.

### Weekly Programming Assignments (WPAs) and final assignment
During each class, you will work on a series of programming tasks, or **Weekly Programming Assignment (WPA)**. You can do it alone, but I encourage you to discuss and/or work with the people around you. It is however very important that each student's work is his/her own. Do not turn in any assignments that you did not contribute to or do not fully understand. **Also, do not forget to maintain phisical distances and to wear a mask at all times**.

By the end of the lesson, you should email your WPA to me to receive credit. While I will keep track of how often you submit your WPAs, I will not grade them. You should however try to reply to each of the questions in the assignment. When you are not able to, I will be there to answer any doubt or question about the code. These assignments are meant as a learning-by-doing exercise.

In the last part of the course, the final assignment will consist in programming an experiment from scratch and to present it to the class. You can decide whether you prefer to do it alone or in pairs. Depending on how many single persons/pairs of students will present, we might take the last 2 to 3 lessons for this.

### Grading
This is a pass / fail course. To pass the course, you should turn in your WPAs, miss not more than 2 classes, and complete your final assignments.

### Additional credits
In this course, it is possible to gain 2 extra credits, by completing a graded assignment. This assignment will consist in programming an experiment from scratch on your own. You should accompany the experiment code (either Inquisit or Psychopy) with a 1 page explanation of the task and how you addressed the assignment requirements. The requirements are to choose an experiment from a peer-reviewed article in a psychology journal, which includes both within- and across-subjects manipulations and repeated measures. Before starting programming such experiment, you should send me a proposal in which you explain to me which experiment you chose and providing a short explanation of the experiment. The deadline for the proposal is the **25 of October**. The deadline for the first version of the thesis (written part + code) is the **20 of December**. I will then review it and give you the chance to improve it. The final deadline is the **10 of January**.