---
title: "Introduction to Inquisit"
---

Here is your first WPA! Today we are going to run a sample script from a choice experiment. To get the script, click on [Download Test for Inquisit 5 ](https://www.millisecond.com/download/library/framing) in the Millisecond Test Library website.

# 1. Run the experiment

The first thing we'll do is participating in the experiment yourself, so you can see how it works. Once you have downloaded the `.iqx` file (the extension for Inquisit's scripts), open it in Inquisit. To run it, just press the green arrow at the top. You'll be prompted to enter a participant number before the experiment begins (any number is fine).

NOTE: If you need to **quit the experiment** press `ctrl + q`.

# 2. Read the user manual

All experiments in the Millisecond Test Library website are provided with a user manual, that usually describes the experiment, tells us from which study it has been taken from, and gives us information on the experimental design and structure of the task.

Find the `<usermanual>` element and read it to familiarize yourself with the framing task.

# 3. Changing the number of trials

The number of trials is defined at the block level. In this case, there is only one block, called `framing`, made of 25 trials.

Find the `<block framing>` element.

`/ trials = [1-25 = choice]` means that the trials from 1 to 25 will be trials of the type `choice`.

What do you think you have to change in order to have 5 trials instead? Try that out and run the experiment again to verify that it worked.

# 4. Changing the stimuli

The stimuli (in this case the different payoffs and odds of the gambles) are defined in the `<list>` elements. There are four lists: one for the odds of gamble A, one for the payoffs of gamble A, one for the odds of gamble B, and one for the payoffs of gamble B. First of all, find these lists in the script.

As you can see, the order of the numbers within the lists matters: When `oddsa` is 30, for example, then `payoffa` is 70, `oddsb` is 70, and `payoffb` is 30.

Modify these lists, either by slightly changing the numbers (for example, to 5-15-25-35-65-75-85-95) or by removing some numbers (for example, to 10-30-70-90). Careful to change the numbers in all 4 lists accordingly : The expected value of A and B should be the same in every trial and one should have high-payoff/low-odd while the other has low-payoff/high-odd).

Run again the experiment to verify that it worked.

# 5. Changing the instructions

The experiment does not have instructions yet.

We can create a `<page>` by adding this in the script:

```
<page start_practice>
In this task, you will be asked to repeatedly choose between two otpions...

^^ jhdfljhdslg

^^ haklshdg

</page>
```

We also have to tell Inquisit to show this page at the beginning of the framing block. Go back to the the `<block framing>` element, and add a line *within* the element itself:

`/preinstructions = (page.start_practice)`

Now run the experiment to see whether it worked. 

Then, fill in some text in order to briefly explain to the participants what kind of task they are going to do.

# 6. Continue Exploring

Try playing around with other elements of the code. Or try out another experiment from the [Millisecond test Library](http://www.millisecond.com/download/library/). 

You can also have a look at the data files. How does the output look? 

# Send me your assignment!

As explained in the syllabus, it is important that you send me your WPA (to my email address: laura.fontanesi@unibas.ch) for each class. As you are supposed to finish this in class, the deadline for sending the assignment is the **same day** of the class.

For this assignment, please send me the Inquisit script. If you want to add comments, you can do that by adding the hashtag `#` at the beginning of the line.

The file name should be: `2_FirstLast.iqx`, where First is your first name and Last is your last name.